#!/usr/bin/env python3
"""Keep the shop page's hidden product list in step with products.json.

shop.html draws its grid with JavaScript from products.json, so tools that read the raw page
(AI assistants, some crawlers) see no products. This writes a <noscript> list of the pieces on sale
(name, description, price, link) into shop.html between the SHOP-NOSCRIPT markers.

  python3 tools/shop_noscript.py          # rewrite the list
  python3 tools/shop_noscript.py --check  # exit 1 if the list is out of date (run before pushing)
"""
import html, json, re, sys

JAPAN_ONLY = {'VNSH', 'LIMINAL LAMP S'}   # same list as JAPAN_ONLY in script.js

def build():
    items = []
    seen_japan_only = set()
    for p in json.load(open('products.json')):
        if (p.get('status') or 'available') not in ('available', 'sold_out'):
            continue
        page = open(p['page']).read()
        m = re.search(r'<meta name="description" content="([^"]*)"', page)
        if not m:
            sys.exit(f"no description meta in {p['page']}")
        desc = html.unescape(m.group(1))
        href = '/' + p['page'].removesuffix('.html')
        note = ' Sold out.' if p.get('status') == 'sold_out' else ''
        # JAPAN_ONLY is keyed by the Checkout button's data-product-id (what script.js reads),
        # not by products.json's id, which differs for some pieces.
        btn = re.search(r'class="add-to-cart"[^>]*data-product-id="([^"]+)"', page)
        pid = btn.group(1) if btn else None
        if pid in JAPAN_ONLY:
            seen_japan_only.add(pid)
        ship = ' Ships within Japan only.' if pid in JAPAN_ONLY else ''
        items.append(f'                <li><a href="{href}">{html.escape(p["name"])}</a>, {html.escape(p["price"])}. '
                     f'{html.escape(desc)}{ship}{note}</li>')
    missing = JAPAN_ONLY - seen_japan_only
    if missing:
        sys.exit(f'Japan-only pieces not found on any shop page: {sorted(missing)} (check JAPAN_ONLY here and in script.js)')
    return ('    <!-- SHOP-NOSCRIPT start: generated by tools/shop_noscript.py from products.json, do not edit by hand -->\n'
            '    <noscript>\n'
            '        <section class="shop-text">\n'
            '            <p>Furniture, lighting and objects by SOTANAKA (Soichiro Tanaka, Tokyo), available to order. '
            'Prices include Japanese consumption tax. Shipping within Japan is free; international shipping '
            'is calculated at checkout.</p>\n'
            '            <ul>\n' + '\n'.join(items) + '\n            </ul>\n'
            '        </section>\n'
            '    </noscript>\n'
            '    <!-- SHOP-NOSCRIPT end -->\n')

js = re.search(r"const JAPAN_ONLY = \[([^\]]*)\]", open('script.js').read())
if not js or set(re.findall(r"'([^']+)'", js.group(1))) != JAPAN_ONLY:
    sys.exit('JAPAN_ONLY in script.js differs from tools/shop_noscript.py: update both')

s = open('shop.html').read()
block = build()
pat = re.compile(r'    <!-- SHOP-NOSCRIPT start.*?<!-- SHOP-NOSCRIPT end -->\n', re.S)
if '--check' in sys.argv:
    cur = pat.search(s)
    if not cur or cur.group(0) != block:
        sys.exit('shop.html hidden product list is out of date: run python3 tools/shop_noscript.py')
    print('shop.html hidden product list matches products.json')
    sys.exit(0)
if pat.search(s):
    s = pat.sub(lambda m: block, s)
else:
    anchor = '    <div class="top-images"></div>\n'
    if s.count(anchor) != 1:
        sys.exit('could not find the shop grid in shop.html')
    s = s.replace(anchor, anchor + block)
open('shop.html', 'w').write(s)
print('wrote', block.count('<li>'), 'products')
